In [1]:
import sys
!{sys.executable} -m pip install geopy
!{sys.executable} -m pip install pandas
# !{sys.executable} -m pip install tensorflow
# !{sys.executable} -m pip install tensorflow-macos
# !{sys.executable} -m pip install tensorflow-metal
#!{sys.executable} -m pip install tensorflow

Requirement already satisfied: geopy in /opt/homebrew/anaconda3/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from geopy) (2.0)
Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#import pandas library
import pandas as pd
from geopy.geocoders import Nominatim

In [3]:
#read in csv file from directory
agmp_data_01 = pd.read_csv("first_import_job_run_error_fix.csv")

In [4]:
#display contents of the csv file

##### renaming columns ############

# Pubmed_id = Publication_ID
# phenotype = phenT
agmp_data_01

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,IUPAC_name,country_participant_01,country_participant_02,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,rs678849,30368523,Genotype CC is associated with decreased respo...,USA,African-American / Afro-Caribbean,African American,False,0.021,OPRD1,NaN,...,"(2S)-2-[(5R,6R,7R,14S)-17-cyclopropylmethyl-4,...",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1903,rs678849,30368523,Genotype CC is not associated with response to...,USA,African-American / Afro-Caribbean,African American,False,0.087,OPRD1,NaN,...,"6-(dimethylamino)-4,4-diphenylheptan-3-one",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1904,rs202201137,30518301,Allele G is associated with decreased dose of ...,Puerto Rico,African-American / Afro-Caribbean,NR,False,NR,CYP2C9,NaN,...,4-hydroxy-3-(3-oxo-1-phenylbutyl)-2H-chromen-2...,Puerto Rico,NaN,NaN,18.224771,-66.485829,NaN,NaN,NaN,NaN
1905,rs5333,30672385,Genotypes CC + TC is associated with increased...,Egypt,North Africa,NR,True,0.228,EDNRA,NaN,...,NaN,Egypt,NaN,NaN,26.254049,29.267547,NaN,NaN,NaN,NaN
1906,rs2273897,30767719,Genotype TT is associated with increased conce...,Nigeria,West Africa,NR,False,0.028,ABCC2,NaN,...,"4-amino-5-fluoro-1-[(2R,5S)-2-(hydroxymethyl)-...",Nigeria,NaN,NaN,9.600036,7.999972,NaN,NaN,NaN,NaN

In [5]:
# convert the csv file into a data frame
df = pd.DataFrame(agmp_data_01)

In [6]:
# display the contents of the dataframe
df

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,IUPAC_name,country_participant_01,country_participant_02,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,rs678849,30368523,Genotype CC is associated with decreased respo...,USA,African-American / Afro-Caribbean,African American,False,0.021,OPRD1,NaN,...,"(2S)-2-[(5R,6R,7R,14S)-17-cyclopropylmethyl-4,...",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1903,rs678849,30368523,Genotype CC is not associated with response to...,USA,African-American / Afro-Caribbean,African American,False,0.087,OPRD1,NaN,...,"6-(dimethylamino)-4,4-diphenylheptan-3-one",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1904,rs202201137,30518301,Allele G is associated with decreased dose of ...,Puerto Rico,African-American / Afro-Caribbean,NR,False,NR,CYP2C9,NaN,...,4-hydroxy-3-(3-oxo-1-phenylbutyl)-2H-chromen-2...,Puerto Rico,NaN,NaN,18.224771,-66.485829,NaN,NaN,NaN,NaN
1905,rs5333,30672385,Genotypes CC + TC is associated with increased...,Egypt,North Africa,NR,True,0.228,EDNRA,NaN,...,NaN,Egypt,NaN,NaN,26.254049,29.267547,NaN,NaN,NaN,NaN
1906,rs2273897,30767719,Genotype TT is associated with increased conce...,Nigeria,West Africa,NR,False,0.028,ABCC2,NaN,...,"4-amino-5-fluoro-1-[(2R,5S)-2-(hydroxymethyl)-...",Nigeria,NaN,NaN,9.600036,7.999972,NaN,NaN,NaN,NaN

In [7]:
# split the column "origin_of_participants" into columns separated by a ,
split_values = df['origin_of_participants'].str.split(',', expand=True)

In [8]:
split_values = split_values.replace(['NR', 'nr'], '')

In [9]:
# display the split values
split_values

                 0     1     2
0     South Africa  None  None
1     South Africa  None  None
2     South Africa  None  None
3     South Africa  None  None
4     South Africa  None  None
...            ...   ...   ...
1902           USA  None  None
1903           USA  None  None
1904   Puerto Rico  None  None
1905         Egypt  None  None
1906       Nigeria  None  None

[1907 rows x 3 columns]

In [10]:

# rename the column names
split_values.columns = [f'country_participant_0{i+1}' for i in range(split_values.shape[1])]

In [11]:
split_values.columns

Index(['country_participant_01', 'country_participant_02',
       'country_participant_03'],
      dtype='object')

In [12]:

# Concatenate the split with the original data frame
result_df = pd.concat([df, split_values], axis=1)

In [13]:
result_df.head()

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03,country_participant_01,country_participant_02,country_participant_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None

In [14]:
result_df.columns

Index(['id', 'Pubmed_id', 'phenotype', 'origin_of_participants',
       'geographical_region', 'Ethnicity', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'Notes', 'study_type', 'gene_symbol_mined',
       'gene_name', 'chromosome', 'uniprot', 'function', 'data_ac',
       'publication_type', 'title', 'publication', 'publication_year',
       'source', 'id_in_source', 'variant_type', 'drug_name', 'ID Drug bank',
       'state', 'Indication', 'IUPAC_name', 'country_participant_01',
       'country_participant_02', 'country_participant_03', 'latitude_01',
       'longitude_01', 'latitude_02', 'longitude_02', 'latitude_03',
       'longitude_03', 'country_participant_01', 'country_participant_02',
       'country_participant_03'],
      dtype='object')

In [15]:
result_df

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03,country_participant_01,country_participant_02,country_participant_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN,South Africa,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,rs678849,30368523,Genotype CC is associated with decreased respo...,USA,African-American / Afro-Caribbean,African American,False,0.021,OPRD1,NaN,...,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN,USA,None,None
1903,rs678849,30368523,Genotype CC is not associated with response to...,USA,African-American / Afro-Caribbean,African American,False,0.087,OPRD1,NaN,...,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN,USA,None,None
1904,rs202201137,30518301,Allele G is associated with decreased dose of ...,Puerto Rico,African-American / Afro-Caribbean,NR,False,NR,CYP2C9,NaN,...,NaN,18.224771,-66.485829,NaN,NaN,NaN,NaN,Puerto Rico,None,None
1905,rs5333,30672385,Genotypes CC + TC is associated with increased...,Egypt,North Africa,NR,True,0.228,EDNRA,NaN,...,NaN,26.254049,29.267547,NaN,NaN,NaN,NaN,Egypt,None,None
1906,rs2273897,30767719,Genotype TT is associated with increased conce...,Nigeria,West Africa,NR,False,0.028,ABCC2,NaN,...,NaN,9.600036,7.999972,NaN,NaN,NaN,NaN,Nigeria,None,None

In [16]:
# =========================================================
# Geocoding with dual geocoder fallback (fixed, robust, and ordered output)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. DataFrame & column safety checks
# =========================================================
if 'result_df' not in globals():
    raise NameError("result_df is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate column names to avoid Series/DataFrame confusion
result_df = result_df.loc[:, ~result_df.columns.duplicated()]

if 'country_participant_01' not in result_df.columns:
    raise KeyError("Column 'country_participant_01' not found in result_df.")

# Force selection as a Series (avoids .unique() error)
country_series = pd.Series(result_df['country_participant_01'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = country_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp01")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary attempt: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback attempt: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    # If all fail
    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
result_df['latitude_01'] = result_df['country_participant_01'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0]
)

result_df['longitude_01'] = result_df['country_participant_01'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1]
)

# Ensure proper numeric dtypes
result_df['latitude_01'] = pd.to_numeric(result_df['latitude_01'], errors='coerce')
result_df['longitude_01'] = pd.to_numeric(result_df['longitude_01'], errors='coerce')

# =========================================================
# 8. Success rate
# =========================================================
successful_geocodes = result_df['latitude_01'].notna().sum()
total_rows = len(result_df)
success_rate = (successful_geocodes / total_rows) * 100

print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_rows} ({success_rate:.1f}%)")

# =========================================================
# 9. (Optional) Save results
# =========================================================
# result_df.to_csv("geocoded_results.csv", index=False)
# print("Results saved to geocoded_results.csv")

Processing 38 valid addresses out of 38 total unique entries.
✓ 1/38: South Africa (Nominatim)
✓ 2/38: Ghana (Nominatim)
✓ 3/38: Tunisia (Nominatim)
✓ 4/38: Algeria (Nominatim)
✓ 5/38: Germany (Nominatim)
  Progress: 5/38 completed in 9.2s
✓ 6/38: Morocco (Nominatim)
✓ 7/38: Lybia (Nominatim)
✓ 8/38: Israel (Nominatim)
✓ 9/38: France (Nominatim)
✓ 10/38: Egypt (Nominatim)
  Progress: 10/38 completed in 17.3s
✓ 11/38: Morrocco (Nominatim)
✓ 12/38: Ethiopia (Nominatim)
✓ 13/38: Mauritius (Nominatim)
✓ 14/38: Tanzania (Nominatim)
✓ 15/38: USA (Nominatim)
  Progress: 15/38 completed in 23.0s
✓ 16/38: Morroco (Nominatim)
✓ 17/38: Benin (Nominatim)
✓ 18/38: United Kingdom (Nominatim)
✓ 19/38: Canada (Nominatim)
✓ 20/38: South African (Nominatim)
  Progress: 20/38 completed in 31.0s
✓ 21/38: Nigeria (Nominatim)
✓ 22/38: Zimbabwe (Nominatim)
✓ 23/38: Brazil (Nominatim)
✓ 24/38: Gambia (Nominatim)
✓ 25/38: Switzerland (Nominatim)
  Progress: 25/38 completed in 36.3s
✓ 26/38: Somali (Nominatim)
✓ 27/38: Uganda (Nominatim)
✓ 28/38: Sudan (Nominatim)
✓ 29/38: Malawi (Nominatim)
✓ 30/38: Rwanda (Nominatim)
  Progress: 30/38 completed in 42.7s
✓ 31/38: NS (Nominatim)
✓ 32/38: Trinidad (Nominatim)
✓ 33/38: Kenya (Nominatim)
✓ 34/38: Cameroon (Nominatim)
✓ 35/38: UK (Nominatim)
  Progress: 35/38 completed in 48.5s
✓ 36/38: Botswana (Nominatim)
✓ 37/38: Tunisian (Nominatim)
✓ 38/38: Puerto Rico (Nominatim)

Geocoding completed! Success rate: 1907/1907 (100.0%)

/var/folders/98/x1h0jc3x43v852q3w4rdc88h0000gn/T/ipykernel_72448/2612405413.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['latitude_01'] = result_df['country_participant_01'].map(
/var/folders/98/x1h0jc3x43v852q3w4rdc88h0000gn/T/ipykernel_72448/2612405413.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['longitude_01'] = result_df['country_participant_01'].map(
/var/folders/98/x1h0jc3x43v852q3w4rdc88h0000gn/T/ipykernel_72448/2612405413.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['latitude_01'] = pd.to_numeric(result_df['latitude_01'], errors='coerce')
/var/folders/98/x1h0jc3x43v852q3w4rdc88h0000gn/T/ipykernel_72448/2612405413.py:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['longitude_01'] = pd.to_numeric(result_df['longitude_01'], errors='coerce')

In [17]:
result_df.loc[:,["latitude_01","longitude_01"]]

      latitude_01  longitude_01
0      -28.816624     24.991639
1      -28.816624     24.991639
2      -28.816624     24.991639
3      -28.816624     24.991639
4      -28.816624     24.991639
...           ...           ...
1902    39.783730   -100.445882
1903    39.783730   -100.445882
1904    18.224771    -66.485829
1905    26.254049     29.267547
1906     9.600036      7.999972

[1907 rows x 2 columns]

In [18]:
result_df

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,IUPAC_name,country_participant_01,country_participant_02,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,rs678849,30368523,Genotype CC is associated with decreased respo...,USA,African-American / Afro-Caribbean,African American,False,0.021,OPRD1,NaN,...,"(2S)-2-[(5R,6R,7R,14S)-17-cyclopropylmethyl-4,...",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1903,rs678849,30368523,Genotype CC is not associated with response to...,USA,African-American / Afro-Caribbean,African American,False,0.087,OPRD1,NaN,...,"6-(dimethylamino)-4,4-diphenylheptan-3-one",USA,NaN,NaN,39.783730,-100.445882,NaN,NaN,NaN,NaN
1904,rs202201137,30518301,Allele G is associated with decreased dose of ...,Puerto Rico,African-American / Afro-Caribbean,NR,False,NR,CYP2C9,NaN,...,4-hydroxy-3-(3-oxo-1-phenylbutyl)-2H-chromen-2...,Puerto Rico,NaN,NaN,18.224771,-66.485829,NaN,NaN,NaN,NaN
1905,rs5333,30672385,Genotypes CC + TC is associated with increased...,Egypt,North Africa,NR,True,0.228,EDNRA,NaN,...,NaN,Egypt,NaN,NaN,26.254049,29.267547,NaN,NaN,NaN,NaN
1906,rs2273897,30767719,Genotype TT is associated with increased conce...,Nigeria,West Africa,NR,False,0.028,ABCC2,NaN,...,"4-amino-5-fluoro-1-[(2R,5S)-2-(hydroxymethyl)-...",Nigeria,NaN,NaN,9.600036,7.999972,NaN,NaN,NaN,NaN

In [19]:
# =========================================================
# Geocoding with dual geocoder fallback (fixed, robust, and ordered output)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. DataFrame & column safety checks
# =========================================================
if 'result_df' not in globals():
    raise NameError("result_df is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate column names to avoid Series/DataFrame confusion
result_df = result_df.loc[:, ~result_df.columns.duplicated()]

if 'country_participant_02' not in result_df.columns:
    raise KeyError("Column 'country_participant_02' not found in result_df.")

# Force selection as a Series (avoids .unique() error)
country_series = pd.Series(result_df['country_participant_01'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = country_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp02")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary attempt: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback attempt: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    # If all fail
    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
result_df['latitude_02'] = result_df['country_participant_02'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0]
)

result_df['longitude_02'] = result_df['country_participant_02'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1]
)

# Ensure proper numeric dtypes
result_df['latitude_02'] = pd.to_numeric(result_df['latitude_02'], errors='coerce')
result_df['longitude_02'] = pd.to_numeric(result_df['longitude_02'], errors='coerce')

# =========================================================
# 8. Success rate
# =========================================================
successful_geocodes = result_df['latitude_02'].notna().sum()
total_rows = len(result_df)
success_rate = (successful_geocodes / total_rows) * 100

print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_rows} ({success_rate:.1f}%)")

# =========================================================
# 9. (Optional) Save results
# =========================================================
# result_df.to_csv("geocoded_results.csv", index=False)
# print("Results saved to geocoded_results.csv")

Processing 38 valid addresses out of 38 total unique entries.
✓ 1/38: South Africa (Nominatim)
✓ 2/38: Ghana (Nominatim)
✓ 3/38: Tunisia (Nominatim)
✓ 4/38: Algeria (Nominatim)
✓ 5/38: Germany (Nominatim)
  Progress: 5/38 completed in 5.8s
✓ 6/38: Morocco (Nominatim)
✓ 7/38: Lybia (Nominatim)
✓ 8/38: Israel (Nominatim)
✓ 9/38: France (Nominatim)
✓ 10/38: Egypt (Nominatim)
  Progress: 10/38 completed in 11.5s
✓ 11/38: Morrocco (Nominatim)
✓ 12/38: Ethiopia (Nominatim)
✓ 13/38: Mauritius (Nominatim)
✓ 14/38: Tanzania (Nominatim)
✓ 15/38: USA (Nominatim)
  Progress: 15/38 completed in 17.9s
✓ 16/38: Morroco (Nominatim)
✓ 17/38: Benin (Nominatim)
✓ 18/38: United Kingdom (Nominatim)
✓ 19/38: Canada (Nominatim)
✓ 20/38: South African (Nominatim)
  Progress: 20/38 completed in 24.6s
✓ 21/38: Nigeria (Nominatim)
✓ 22/38: Zimbabwe (Nominatim)
✓ 23/38: Brazil (Nominatim)
✓ 24/38: Gambia (Nominatim)
✓ 25/38: Switzerland (Nominatim)
  Progress: 25/38 completed in 30.5s
✓ 26/38: Somali (Nominatim)
✓ 27/38: Uganda (Nominatim)
✓ 28/38: Sudan (Nominatim)
✓ 29/38: Malawi (Nominatim)
✓ 30/38: Rwanda (Nominatim)
  Progress: 30/38 completed in 36.8s
✓ 31/38: NS (Nominatim)
✓ 32/38: Trinidad (Nominatim)
✓ 33/38: Kenya (Nominatim)
✓ 34/38: Cameroon (Nominatim)
✓ 35/38: UK (Nominatim)
  Progress: 35/38 completed in 42.6s
✓ 36/38: Botswana (Nominatim)
✓ 37/38: Tunisian (Nominatim)
✓ 38/38: Puerto Rico (Nominatim)

Geocoding completed! Success rate: 45/1907 (2.4%)

In [20]:
result_df.loc[:,["latitude_02","longitude_02"]]

      latitude_02  longitude_02
0             NaN           NaN
1             NaN           NaN
2             NaN           NaN
3             NaN           NaN
4             NaN           NaN
...           ...           ...
1902          NaN           NaN
1903          NaN           NaN
1904          NaN           NaN
1905          NaN           NaN
1906          NaN           NaN

[1907 rows x 2 columns]

In [21]:
# =========================================================
# Geocoding with dual geocoder fallback (fixed, robust, and ordered output)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. DataFrame & column safety checks
# =========================================================
if 'result_df' not in globals():
    raise NameError("result_df is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate column names to avoid Series/DataFrame confusion
result_df = result_df.loc[:, ~result_df.columns.duplicated()]

if 'country_participant_03' not in result_df.columns:
    raise KeyError("Column 'country_participant_01' not found in result_df.")

# Force selection as a Series (avoids .unique() error)
country_series = pd.Series(result_df['country_participant_01'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = country_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp03")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary attempt: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback attempt: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    # If all fail
    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
result_df['latitude_03'] = result_df['country_participant_03'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0]
)

result_df['longitude_03'] = result_df['country_participant_03'].map(
    lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1]
)

# Ensure proper numeric dtypes
result_df['latitude_03'] = pd.to_numeric(result_df['latitude_03'], errors='coerce')
result_df['longitude_03'] = pd.to_numeric(result_df['longitude_03'], errors='coerce')

# =========================================================
# 8. Success rate
# =========================================================
successful_geocodes = result_df['latitude_03'].notna().sum()
total_rows = len(result_df)
success_rate = (successful_geocodes / total_rows) * 100

print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_rows} ({success_rate:.1f}%)")

# =========================================================
# 9. (Optional) Save results
# =========================================================
# result_df.to_csv("geocoded_results.csv", index=False)
# print("Results saved to geocoded_results.csv")

Processing 38 valid addresses out of 38 total unique entries.
✓ 1/38: South Africa (Nominatim)
✓ 2/38: Ghana (Nominatim)
✓ 3/38: Tunisia (Nominatim)
✓ 4/38: Algeria (Nominatim)
✓ 5/38: Germany (Nominatim)
  Progress: 5/38 completed in 6.1s
✓ 6/38: Morocco (Nominatim)
✓ 7/38: Lybia (Nominatim)
✓ 8/38: Israel (Nominatim)
✓ 9/38: France (Nominatim)
✓ 10/38: Egypt (Nominatim)
  Progress: 10/38 completed in 11.4s
✓ 11/38: Morrocco (Nominatim)
✓ 12/38: Ethiopia (Nominatim)
✓ 13/38: Mauritius (Nominatim)
✓ 14/38: Tanzania (Nominatim)
✓ 15/38: USA (Nominatim)
  Progress: 15/38 completed in 18.1s
✓ 16/38: Morroco (Nominatim)
✓ 17/38: Benin (Nominatim)
✓ 18/38: United Kingdom (Nominatim)
✓ 19/38: Canada (Nominatim)
✓ 20/38: South African (Nominatim)
  Progress: 20/38 completed in 23.6s
✓ 21/38: Nigeria (Nominatim)
✓ 22/38: Zimbabwe (Nominatim)
✓ 23/38: Brazil (Nominatim)
✓ 24/38: Gambia (Nominatim)
✓ 25/38: Switzerland (Nominatim)
  Progress: 25/38 completed in 29.8s
✓ 26/38: Somali (Nominatim)
✓ 27/38: Uganda (Nominatim)
✓ 28/38: Sudan (Nominatim)
✓ 29/38: Malawi (Nominatim)
✓ 30/38: Rwanda (Nominatim)
  Progress: 30/38 completed in 35.6s
✓ 31/38: NS (Nominatim)
✓ 32/38: Trinidad (Nominatim)
✓ 33/38: Kenya (Nominatim)
✓ 34/38: Cameroon (Nominatim)
✓ 35/38: UK (Nominatim)
  Progress: 35/38 completed in 43.4s
✓ 36/38: Botswana (Nominatim)
✓ 37/38: Tunisian (Nominatim)
✓ 38/38: Puerto Rico (Nominatim)

Geocoding completed! Success rate: 22/1907 (1.2%)

In [22]:
result_df.loc[:,["latitude_03","longitude_03"]]

      latitude_03  longitude_03
0             NaN           NaN
1             NaN           NaN
2             NaN           NaN
3             NaN           NaN
4             NaN           NaN
...           ...           ...
1902          NaN           NaN
1903          NaN           NaN
1904          NaN           NaN
1905          NaN           NaN
1906          NaN           NaN

[1907 rows x 2 columns]

In [23]:
result_df.head()

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,IUPAC_name,country_participant_01,country_participant_02,country_participant_03,latitude_01,longitude_01,latitude_02,longitude_02,latitude_03,longitude_03
0,rs267607142,897853,"Progressive Familial Heart Block, Type Ib",South Africa,Southern Africa,NR,False,NS,TRPM4,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
1,rs1800450,1304173,Mannose-Binding Protein Deficiency,South Africa,Southern Africa,NR,False,< 0.0001,MBL2,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
2,rs121907960,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
3,rs121907969,1322637,Tay-Sachs Disease,South Africa,Southern Africa,Jewish,False,NR,HEXA,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN
4,rs28933385,1351274,Prion Diseases,South Africa,Southern Africa,Jewish,False,NS,PRNP,NaN,...,NaN,South Africa,NaN,NaN,-28.816624,24.991639,NaN,NaN,NaN,NaN

In [24]:
column_name = 'phenotype'
result_df[column_name] = result_df[column_name].str.replace("/", ",")
##### code snippet to remove the whole / on the whole column #####

In [25]:
# name the output csv
csv_filename = 'first_import_job_run.csv'

In [26]:
#result of the csv file without the index column
result_df.to_csv(csv_filename, index=False)

In [27]:
print(f"DataFrame exported to /{csv_filename}")

DataFrame exported to /first_import_job_run.csv