In [1]:
import sys
!{sys.executable} -m pip install geopy
!{sys.executable} -m pip install pandas

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/lib/python3.13/site-packages (from geopy) (2.1)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#import pandas library
import pandas as pd
from geopy.geocoders import Nominatim

In [3]:
#read in csv file from directory
agmp_data = pd.read_excel("gwas_data_16092025_combined.xlsx")

In [4]:
import os
file_path = 'gwas_data_16092025_combined.xlsx'
file_size_bytes = os.path.getsize(file_path)

file_size_kb = file_size_bytes / 1024
print(f"The size of the file is: {file_size_kb:.2f} KB")

The size of the file is: 124664.46 KB

In [5]:

agmp_data

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,data_ac,publication_type,title,publication,publication_year,source,id_in_source,variant_type,intergenic,gene_symbol_external
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.00000,"G6PC2, SPC25",GWAS,NaN,...,2025-07-23,PubMed,"GWAS of random glucose in 476,326 individuals ...",37679419,2023,GWAS Catalog,GCST90271558,SNV,0,G6PC2
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.00000,LINC02283 - LINC02260,GWAS,NR,...,2025-07-23,PubMed,Trans-ethnic and Ancestry-Specific Blood-Cell ...,32888493,2020,GWAS Catalog,GCST90002367,SNV,1,NaN
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.00000,IL12B - LINC01845,GWAS,NaN,...,2025-07-23,PubMed,Genetics of circulating inflammatory proteins ...,37563310,2023,GWAS Catalog,GCST90274798,SNV,1,NaN
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209043,rs112826792,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,UBE2V1P12 - Metazoa_SRP,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,1,NaN
209044,rs12153707,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,SPOCK1,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,0,SPOCK1
209045,rs9662820,39046104,Vascular dementia,"U.S., NR","African-American / Afro-Caribbean, NR",True,0.00001,CHRM3,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association meta-analysis of all...,39046104,2024,GWAS Catalog,GCST90449023,SNV,0,CHRM3
209046,rs144927963,36210801,RS-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,"AP1B1P1, AP1B1P1",GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129567,SNV,0,NaN
209047,rs11837984,36210801,R-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,NCOR2,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129566,SNV,0,NCOR2

In [6]:

agmp_data_wip = agmp_data

In [7]:
agmp_data_wip

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,data_ac,publication_type,title,publication,publication_year,source,id_in_source,variant_type,intergenic,gene_symbol_external
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.00000,"G6PC2, SPC25",GWAS,NaN,...,2025-07-23,PubMed,"GWAS of random glucose in 476,326 individuals ...",37679419,2023,GWAS Catalog,GCST90271558,SNV,0,G6PC2
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.00000,LINC02283 - LINC02260,GWAS,NR,...,2025-07-23,PubMed,Trans-ethnic and Ancestry-Specific Blood-Cell ...,32888493,2020,GWAS Catalog,GCST90002367,SNV,1,NaN
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.00000,IL12B - LINC01845,GWAS,NaN,...,2025-07-23,PubMed,Genetics of circulating inflammatory proteins ...,37563310,2023,GWAS Catalog,GCST90274798,SNV,1,NaN
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209043,rs112826792,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,UBE2V1P12 - Metazoa_SRP,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,1,NaN
209044,rs12153707,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,SPOCK1,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,0,SPOCK1
209045,rs9662820,39046104,Vascular dementia,"U.S., NR","African-American / Afro-Caribbean, NR",True,0.00001,CHRM3,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association meta-analysis of all...,39046104,2024,GWAS Catalog,GCST90449023,SNV,0,CHRM3
209046,rs144927963,36210801,RS-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,"AP1B1P1, AP1B1P1",GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129567,SNV,0,NaN
209047,rs11837984,36210801,R-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,NCOR2,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129566,SNV,0,NCOR2

In [8]:
# # convert the csv file into a data frame
# df = pd.DataFrame(agmp_data)

In [9]:
# # display the contents of the dataframe
# df

In [10]:
agmp_data_wip

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,data_ac,publication_type,title,publication,publication_year,source,id_in_source,variant_type,intergenic,gene_symbol_external
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.00000,"G6PC2, SPC25",GWAS,NaN,...,2025-07-23,PubMed,"GWAS of random glucose in 476,326 individuals ...",37679419,2023,GWAS Catalog,GCST90271558,SNV,0,G6PC2
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.00000,LINC02283 - LINC02260,GWAS,NR,...,2025-07-23,PubMed,Trans-ethnic and Ancestry-Specific Blood-Cell ...,32888493,2020,GWAS Catalog,GCST90002367,SNV,1,NaN
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.00000,IL12B - LINC01845,GWAS,NaN,...,2025-07-23,PubMed,Genetics of circulating inflammatory proteins ...,37563310,2023,GWAS Catalog,GCST90274798,SNV,1,NaN
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.00000,LPA,GWAS,NR,...,2025-07-23,PubMed,Genetics of 35 blood and urine biomarkers in t...,33462484,2021,GWAS Catalog,GCST90019513,SNV,0,LPA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209043,rs112826792,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,UBE2V1P12 - Metazoa_SRP,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,1,NaN
209044,rs12153707,37984853,Baseline memory in impaired cognition x sex in...,NR,NR,False,0.00001,SPOCK1,GWAS,NaN,...,2025-07-23,PubMed,Sex-specific genetic architecture of late-life...,37984853,2023,GWAS Catalog,GCST90448440,SNV,0,SPOCK1
209045,rs9662820,39046104,Vascular dementia,"U.S., NR","African-American / Afro-Caribbean, NR",True,0.00001,CHRM3,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association meta-analysis of all...,39046104,2024,GWAS Catalog,GCST90449023,SNV,0,CHRM3
209046,rs144927963,36210801,RS-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,"AP1B1P1, AP1B1P1",GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129567,SNV,0,NaN
209047,rs11837984,36210801,R-6-hydroxywarfarin levels,"South Africa, Uganda","East Africa, Southern Africa",True,0.00001,NCOR2,GWAS,NaN,...,2025-07-23,PubMed,A genome-wide association study of plasma conc...,36210801,2022,GWAS Catalog,GCST90129566,SNV,0,NCOR2

In [11]:


# split the column "origin_of_participants" into columns separated by a ,
split_values = agmp_data_wip['origin_of_participants'].str.split(',', expand=True)

In [12]:
split_values = split_values.replace(['NR', 'nr'], '')

In [13]:
# display the split values
split_values

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,U.K.,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,U.K.,Japan,China,Estonia,U.S.,Finland,Canada,Netherlands,Germany,None,...,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209043,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
209044,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
209045,U.S.,NR,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
209046,South Africa,Uganda,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
209047,South Africa,Uganda,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [14]:
 
# rename the column names
split_values.columns = [f'country_participant_0{i+1}' for i in range(split_values.shape[1])]

In [15]:
split_values.columns

Index(['country_participant_01', 'country_participant_02',
       'country_participant_03', 'country_participant_04',
       'country_participant_05', 'country_participant_06',
       'country_participant_07', 'country_participant_08',
       'country_participant_09', 'country_participant_010',
       'country_participant_011', 'country_participant_012',
       'country_participant_013', 'country_participant_014',
       'country_participant_015', 'country_participant_016',
       'country_participant_017', 'country_participant_018',
       'country_participant_019', 'country_participant_020',
       'country_participant_021', 'country_participant_022',
       'country_participant_023', 'country_participant_024',
       'country_participant_025', 'country_participant_026',
       'country_participant_027', 'country_participant_028',
       'country_participant_029', 'country_participant_030',
       'country_participant_031', 'country_participant_032',
       'country_participant_033', 'country_participant_034',
       'country_participant_035', 'country_participant_036',
       'country_participant_037', 'country_participant_038',
       'country_participant_039', 'country_participant_040',
       'country_participant_041'],
      dtype='object')

In [16]:

# Concatenate the split with the original data frame
result_df = pd.concat([agmp_data_wip, split_values], axis=1)

In [17]:
result_df.head()

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,country_participant_032,country_participant_033,country_participant_034,country_participant_035,country_participant_036,country_participant_037,country_participant_038,country_participant_039,country_participant_040,country_participant_041
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.0,"G6PC2, SPC25",GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.0,LINC02283 - LINC02260,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.0,IL12B - LINC01845,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.0,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.0,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None

In [18]:
result_df.columns

Index(['id', 'PUBMEDID', 'phenotype', 'origin_of_participants',
       'geographical_region', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'study_type', 'gene_symbol_mined', 'gene_name',
       'chromosome', 'uniprot', 'function', 'data_ac', 'publication_type',
       'title', 'publication', 'publication_year', 'source', 'id_in_source',
       'variant_type', 'intergenic', 'gene_symbol_external',
       'country_participant_01', 'country_participant_02',
       'country_participant_03', 'country_participant_04',
       'country_participant_05', 'country_participant_06',
       'country_participant_07', 'country_participant_08',
       'country_participant_09', 'country_participant_010',
       'country_participant_011', 'country_participant_012',
       'country_participant_013', 'country_participant_014',
       'country_participant_015', 'country_participant_016',
       'country_participant_017', 'country_participant_018',
       'country_participant_019', 'country_participant_020',
       'country_participant_021', 'country_participant_022',
       'country_participant_023', 'country_participant_024',
       'country_participant_025', 'country_participant_026',
       'country_participant_027', 'country_participant_028',
       'country_participant_029', 'country_participant_030',
       'country_participant_031', 'country_participant_032',
       'country_participant_033', 'country_participant_034',
       'country_participant_035', 'country_participant_036',
       'country_participant_037', 'country_participant_038',
       'country_participant_039', 'country_participant_040',
       'country_participant_041'],
      dtype='object')

In [19]:
result_df.columns

Index(['id', 'PUBMEDID', 'phenotype', 'origin_of_participants',
       'geographical_region', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'study_type', 'gene_symbol_mined', 'gene_name',
       'chromosome', 'uniprot', 'function', 'data_ac', 'publication_type',
       'title', 'publication', 'publication_year', 'source', 'id_in_source',
       'variant_type', 'intergenic', 'gene_symbol_external',
       'country_participant_01', 'country_participant_02',
       'country_participant_03', 'country_participant_04',
       'country_participant_05', 'country_participant_06',
       'country_participant_07', 'country_participant_08',
       'country_participant_09', 'country_participant_010',
       'country_participant_011', 'country_participant_012',
       'country_participant_013', 'country_participant_014',
       'country_participant_015', 'country_participant_016',
       'country_participant_017', 'country_participant_018',
       'country_participant_019', 'country_participant_020',
       'country_participant_021', 'country_participant_022',
       'country_participant_023', 'country_participant_024',
       'country_participant_025', 'country_participant_026',
       'country_participant_027', 'country_participant_028',
       'country_participant_029', 'country_participant_030',
       'country_participant_031', 'country_participant_032',
       'country_participant_033', 'country_participant_034',
       'country_participant_035', 'country_participant_036',
       'country_participant_037', 'country_participant_038',
       'country_participant_039', 'country_participant_040',
       'country_participant_041'],
      dtype='object')

In [20]:
agmp_data_wip = result_df.iloc[:200000]

In [21]:
agmp_data_wip.shape
agmp_data_wip

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,country_participant_032,country_participant_033,country_participant_034,country_participant_035,country_participant_036,country_participant_037,country_participant_038,country_participant_039,country_participant_040,country_participant_041
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.000000,"G6PC2, SPC25",GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.000000,LINC02283 - LINC02260,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.000000,IL12B - LINC01845,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.000000,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.000000,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,rs78353857,38469033,Hospitalization rate in serious mental illnesses,U.S.,African-American / Afro-Caribbean,False,0.000007,RABGAP1L,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199996,rs12193070,26198764,Schizophrenia,U.S.,African-American / Afro-Caribbean,False,0.000007,LINC02549,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
199997,rs61898332,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,MS4A5,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199998,rs11080114,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,EFCAB5,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199999,rs10188091,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,PRKCE,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None

In [22]:
agmp_data_wip

,id,PUBMEDID,phenotype,origin_of_participants,geographical_region,mixed_population,p-value,curated_gene_symbol,study_type,gene_symbol_mined,...,country_participant_032,country_participant_033,country_participant_034,country_participant_035,country_participant_036,country_participant_037,country_participant_038,country_participant_039,country_participant_040,country_participant_041
0,rs560887,37679419,Random glucose levels,U.K.,African unspecified,False,0.000000,"G6PC2, SPC25",GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
1,rs1848347,32888493,Red blood cell count,"U.K., Japan, China, Estonia, U.S., Finland, Ca...",African-American / Afro-Caribbean,True,0.000000,LINC02283 - LINC02260,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
2,rs10076557,37563310,Interleukin-12 subunit beta levels,NR,NR,False,0.000000,IL12B - LINC01845,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
3,rs41272114,33462484,Lipoprotein (a) levels,NR,NR,False,0.000000,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
4,rs4708871,33462484,Lipoprotein (a) levels,NR,NR,False,0.000000,LPA,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,rs78353857,38469033,Hospitalization rate in serious mental illnesses,U.S.,African-American / Afro-Caribbean,False,0.000007,RABGAP1L,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199996,rs12193070,26198764,Schizophrenia,U.S.,African-American / Afro-Caribbean,False,0.000007,LINC02549,GWAS,NR,...,None,None,None,None,None,None,None,None,None,None
199997,rs61898332,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,MS4A5,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199998,rs11080114,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,EFCAB5,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None
199999,rs10188091,36662838,Resistance to COVID-19 infection (Exposed nega...,Poland,NR,False,0.000007,PRKCE,GWAS,NaN,...,None,None,None,None,None,None,None,None,None,None

In [23]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_01' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_01' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_01'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp01")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_01'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_01'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_01', 'longitude_01']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_01'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_01'] = pd.to_numeric(agmp_data_wip['latitude_01'], errors='coerce')
agmp_data_wip['longitude_01'] = pd.to_numeric(agmp_data_wip['longitude_01'], errors='coerce')

Processing 89 valid addresses out of 90 total unique entries.
✓ 1/89: U.K. (Nominatim)
✓ 2/89: Russian Federation (Nominatim)
✓ 3/89: Sweden (Nominatim)
✓ 4/89: U.S. (Nominatim)
✓ 5/89: China (Nominatim)
  Progress: 5/89 completed in 5.2s
✓ 6/89: Canada (Nominatim)
✓ 7/89: France (Nominatim)
✓ 8/89: Germany (Nominatim)
✓ 9/89: Argentina (Nominatim)
✓ 10/89: South Africa (Nominatim)
  Progress: 10/89 completed in 10.9s
✓ 11/89: Netherlands (Nominatim)
✓ 12/89: Qatar (Nominatim)
✓ 13/89: Greece (Nominatim)
✓ 14/89: Brazil (Nominatim)
✓ 15/89: Saudi Arabia (Nominatim)
  Progress: 15/89 completed in 17.0s
✓ 16/89: Turkey (Nominatim)
✓ 17/89: Iran (Islamic Republic of) (Nominatim)
✓ 18/89: Finland (Nominatim)
✓ 19/89: Austria (Nominatim)
✓ 20/89: Democratic Republic of the Congo (Nominatim)
  Progress: 20/89 completed in 22.9s
✓ 21/89: Ghana (Nominatim)
✓ 22/89: Kuwait (Nominatim)
✓ 23/89: Mexico (Nominatim)
✓ 24/89: Denmark (Nominatim)
✓ 25/89: Jordan (Nominatim)
  Progress: 25/89 completed in 29.1s
✓ 26/89: Burkina Faso (Nominatim)
✓ 27/89: Uganda (Nominatim)
✓ 28/89: Nigeria (Nominatim)
✓ 29/89: Jamaica (Nominatim)
✓ 30/89: Kenya (Nominatim)
  Progress: 30/89 completed in 35.0s
✓ 31/89: Lebanon (Nominatim)
✓ 32/89: United Republic of Tanzania (Nominatim)
✓ 33/89: Georgia (Nominatim)
✓ 34/89: Australia (Nominatim)
✓ 35/89: Japan (Nominatim)
  Progress: 35/89 completed in 41.1s
✓ 36/89: Poland (Nominatim)
✓ 37/89: Belgium (Nominatim)
✓ 38/89: Senegal (Nominatim)
✓ 39/89: Egypt (Nominatim)
✓ 40/89: Ethiopia (Nominatim)
  Progress: 40/89 completed in 47.0s
✓ 41/89: Israel (Nominatim)
✓ 42/89: Cameroon (Nominatim)
✓ 43/89: Taiwan (Nominatim)
✓ 44/89: Estonia (Nominatim)
✓ 45/89: Romania (Nominatim)
  Progress: 45/89 completed in 53.1s
✓ 46/89: Spain (Nominatim)
✓ 47/89: Colombia (Nominatim)
✓ 48/89: Greenland (Nominatim)
✓ 49/89: Barbados (Nominatim)
✓ 50/89: Malawi (Nominatim)
  Progress: 50/89 completed in 59.0s
✓ 51/89: Norway (Nominatim)
✓ 52/89: Armenia (Nominatim)
✓ 53/89: Yemen (Nominatim)
✓ 54/89: Seychelles (Nominatim)
✓ 55/89: Indonesia (Nominatim)
  Progress: 55/89 completed in 65.2s
✓ 56/89: Gambia (Nominatim)
✓ 57/89: Mali (Nominatim)
✓ 58/89: Italy (Nominatim)
✓ 59/89: Suriname (Nominatim)
✓ 60/89: Guinea-Bissau (Nominatim)
  Progress: 60/89 completed in 71.0s
✓ 61/89: New Zealand (Nominatim)
✓ 62/89: Cape Verde (Nominatim)
✓ 63/89: Hungary (Nominatim)
✓ 64/89: Madagascar (Nominatim)
✓ 65/89: Latvia (Nominatim)
  Progress: 65/89 completed in 77.1s
✓ 66/89: Sierra Leone (Nominatim)
✓ 67/89: Singapore (Nominatim)
✓ 68/89: Nepal (Nominatim)
✓ 69/89: Fiji (Nominatim)
✓ 70/89: Peru (Nominatim)
  Progress: 70/89 completed in 83.2s
✓ 71/89: Philippines (Nominatim)
✓ 72/89: Botswana (Nominatim)
✓ 73/89: United Arab Emirates (Nominatim)
✓ 74/89: Trinidad and Tobago (Nominatim)
✓ 75/89: Kazakhstan (Nominatim)
  Progress: 75/89 completed in 89.1s
✓ 76/89: Republic of Ireland (Nominatim)
✓ 77/89: Benin (Nominatim)
✓ 78/89: Mozambique (Nominatim)
✓ 79/89: Czech Republic (Nominatim)
✓ 80/89: Puerto Rico (Nominatim)
  Progress: 80/89 completed in 95.2s
✓ 81/89: French Polynesia (Nominatim)
✓ 82/89: Slovakia (Nominatim)
✓ 83/89: Netherlands Antilles (Nominatim)
✓ 84/89: Republic of Korea (Nominatim)
✓ 85/89: Chile (Nominatim)
  Progress: 85/89 completed in 101.3s
✓ 86/89: Morocco (Nominatim)
✓ 87/89: Bulgaria (Nominatim)
✓ 88/89: Guatemala (Nominatim)
✓ 89/89: Portugal (Nominatim)

Geocoding completed! Success rate: 122200/122633 (99.6%)
Excluded 77367 records with geographical_region = 'NR'

In [24]:

agmp_data_wip.loc[:,["latitude_01","longitude_01"]]

        latitude_01  longitude_01
0         54.702354     -3.276575
1         54.702354     -3.276575
2               NaN           NaN
3               NaN           NaN
4               NaN           NaN
...             ...           ...
199995    39.783730   -100.445882
199996    39.783730   -100.445882
199997          NaN           NaN
199998          NaN           NaN
199999          NaN           NaN

[200000 rows x 2 columns]

In [25]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_02' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_02' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_02'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp02")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_02'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_02'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_02', 'longitude_02']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_02'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_02'] = pd.to_numeric(agmp_data_wip['latitude_02'], errors='coerce')
agmp_data_wip['longitude_02'] = pd.to_numeric(agmp_data_wip['longitude_02'], errors='coerce')

Processing 74 valid addresses out of 74 total unique entries.
✓ 1/74: Japan (Nominatim)
✓ 2/74: Costa Rica (Nominatim)
✓ 3/74: NR (Nominatim)
✓ 4/74: U.S. (Nominatim)
✓ 5/74: Estonia (Nominatim)
  Progress: 5/74 completed in 4.9s
✓ 6/74: U.K. (Nominatim)
✓ 7/74: Germany (Nominatim)
✓ 8/74: Romania (Nominatim)
✓ 9/74: Jamaica (Nominatim)
✓ 10/74: Netherlands (Nominatim)
  Progress: 10/74 completed in 10.9s
✓ 11/74: Burkina Faso (Nominatim)
✓ 12/74: Saudi Arabia (Nominatim)
✓ 13/74: France (Nominatim)
✓ 14/74: Ghana (Nominatim)
✓ 15/74: Nigeria (Nominatim)
  Progress: 15/74 completed in 17.0s
✓ 16/74: Canada (Nominatim)
✓ 17/74: Iceland (Nominatim)
✓ 18/74: Lebanon (Nominatim)
✓ 19/74: Australia (Nominatim)
✓ 20/74: South Africa (Nominatim)
  Progress: 20/74 completed in 23.0s
✓ 21/74: Iran (Islamic Republic of) (Nominatim)
✓ 22/74: Egypt (Nominatim)
✓ 23/74: Brazil (Nominatim)
✓ 24/74: Barbados (Nominatim)
✓ 25/74: Qatar (Nominatim)
  Progress: 25/74 completed in 29.0s
✓ 26/74: Denmark (Nominatim)
✓ 27/74: Spain (Nominatim)
✓ 28/74: Uganda (Nominatim)
✓ 29/74: Italy (Nominatim)
✓ 30/74: Poland (Nominatim)
  Progress: 30/74 completed in 35.0s
✓ 31/74: Norway (Nominatim)
✓ 32/74: Russian Federation (Nominatim)
✓ 33/74: Puerto Rico (Nominatim)
✓ 34/74: Argentina (Nominatim)
✓ 35/74: Philippines (Nominatim)
  Progress: 35/74 completed in 41.0s
✓ 36/74: Greece (Nominatim)
✓ 37/74: Israel (Nominatim)
✓ 38/74: Finland (Nominatim)
✓ 39/74: China (Nominatim)
✓ 40/74: Gambia (Nominatim)
  Progress: 40/74 completed in 47.0s
✓ 41/74: Cameroon (Nominatim)
✓ 42/74: Hungary (Nominatim)
✓ 43/74: Czech Republic (Nominatim)
✓ 44/74: Kenya (Nominatim)
✓ 45/74: Colombia (Nominatim)
  Progress: 45/74 completed in 53.1s
✓ 46/74: Sweden (Nominatim)
✓ 47/74: Belgium (Nominatim)
✓ 48/74: Niger (Nominatim)
✓ 49/74: Azerbaijan (Nominatim)
✓ 50/74: Georgia (Nominatim)
  Progress: 50/74 completed in 59.2s
✓ 51/74: Bulgaria (Nominatim)
✓ 52/74: Pakistan (Nominatim)
✓ 53/74: Austria (Nominatim)
✓ 54/74: Switzerland (Nominatim)
✓ 55/74: Congo (Nominatim)
  Progress: 55/74 completed in 65.2s
✓ 56/74: Malawi (Nominatim)
✓ 57/74: Turkey (Nominatim)
✓ 58/74: New Zealand (Nominatim)
✓ 59/74: United Republic of Tanzania (Nominatim)
✓ 60/74: Republic of Ireland (Nominatim)
  Progress: 60/74 completed in 71.1s
✓ 61/74: Slovenia (Nominatim)
✓ 62/74: Portugal (Nominatim)
✓ 63/74: Cambodia (Nominatim)
✓ 64/74: New Caledonia (Nominatim)
✓ 65/74: Democratic Republic of the Congo (Nominatim)
  Progress: 65/74 completed in 77.1s
✓ 66/74: Mali (Nominatim)
✓ 67/74: Singapore (Nominatim)
✓ 68/74: Mozambique (Nominatim)
✓ 69/74: Greenland (Nominatim)
✓ 70/74: Slovakia (Nominatim)
  Progress: 70/74 completed in 83.1s
✓ 71/74: Mexico (Nominatim)
✓ 72/74: Republic of Korea (Nominatim)
✓ 73/74: United Arab Emirates (Nominatim)
✓ 74/74: Ethiopia (Nominatim)

Geocoding completed! Success rate: 36037/122633 (29.4%)
Excluded 77367 records with geographical_region = 'NR'

In [26]:
agmp_data_wip.loc[:,["latitude_02","longitude_02"]]

        latitude_02  longitude_02
0               NaN           NaN
1         36.574844    139.239418
2               NaN           NaN
3               NaN           NaN
4               NaN           NaN
...             ...           ...
199995          NaN           NaN
199996          NaN           NaN
199997          NaN           NaN
199998          NaN           NaN
199999          NaN           NaN

[200000 rows x 2 columns]

In [27]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_03' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_03' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_03'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp03")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_03'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_03'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_03', 'longitude_03']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_03'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_03'] = pd.to_numeric(agmp_data_wip['latitude_03'], errors='coerce')
agmp_data_wip['longitude_03'] = pd.to_numeric(agmp_data_wip['longitude_03'], errors='coerce')

Processing 62 valid addresses out of 62 total unique entries.
✓ 1/62: China (Nominatim)
✓ 2/62: Netherlands (Nominatim)
✓ 3/62: Estonia (Nominatim)
✓ 4/62: Canada (Nominatim)
✓ 5/62: U.S. (Nominatim)
  Progress: 5/62 completed in 6.9s
✓ 6/62: South Africa (Nominatim)
✓ 7/62: Uganda (Nominatim)
✓ 8/62: Barbados (Nominatim)
✓ 9/62: Uruguay (Nominatim)
✓ 10/62: Sweden (Nominatim)
  Progress: 10/62 completed in 12.8s
✓ 11/62: Germany (Nominatim)
✓ 12/62: U.K. (Nominatim)
✓ 13/62: Qatar (Nominatim)
✓ 14/62: Kenya (Nominatim)
✓ 15/62: Republic of Ireland (Nominatim)
  Progress: 15/62 completed in 18.9s
✓ 16/62: Austria (Nominatim)
✓ 17/62: Greece (Nominatim)
✓ 18/62: Egypt (Nominatim)
✓ 19/62: Israel (Nominatim)
✓ 20/62: Norway (Nominatim)
  Progress: 20/62 completed in 24.8s
✓ 21/62: NR (Nominatim)
✓ 22/62: Italy (Nominatim)
✓ 23/62: Gambia (Nominatim)
✓ 24/62: Denmark (Nominatim)
✓ 25/62: Ghana (Nominatim)
  Progress: 25/62 completed in 30.9s
✓ 26/62: Switzerland (Nominatim)
✓ 27/62: France (Nominatim)
✓ 28/62: Australia (Nominatim)
✓ 29/62: Finland (Nominatim)
✓ 30/62: Republic of Korea (Nominatim)
  Progress: 30/62 completed in 36.9s
✓ 31/62: Nigeria (Nominatim)
✓ 32/62: Iceland (Nominatim)
✓ 33/62: Belgium (Nominatim)
✓ 34/62: Slovakia (Nominatim)
✓ 35/62: Russian Federation (Nominatim)
  Progress: 35/62 completed in 43.0s
✓ 36/62: Spain (Nominatim)
✓ 37/62: Brazil (Nominatim)
✓ 38/62: Turkey (Nominatim)
✓ 39/62: Guatemala (Nominatim)
✓ 40/62: Niger (Nominatim)
  Progress: 40/62 completed in 49.6s
✓ 41/62: Afghanistan (Nominatim)
✓ 42/62: Zimbabwe (Nominatim)
✓ 43/62: Japan (Nominatim)
✓ 44/62: Guadeloupe (Nominatim)
✓ 45/62: Cameroon (Nominatim)
  Progress: 45/62 completed in 54.9s
✓ 46/62: Mozambique (Nominatim)
✓ 47/62: Ukraine (Nominatim)
✓ 48/62: Hungary (Nominatim)
✓ 49/62: Serbia (Nominatim)
✓ 50/62: Puerto Rico (Nominatim)
  Progress: 50/62 completed in 61.1s
✓ 51/62: Ethiopia (Nominatim)
✓ 52/62: Congo (Nominatim)
✓ 53/62: India (Nominatim)
✓ 54/62: Slovenia (Nominatim)
✓ 55/62: Vanuatu (Nominatim)
  Progress: 55/62 completed in 67.0s
✓ 56/62: Mexico (Nominatim)
✓ 57/62: Azerbaijan (Nominatim)
✓ 58/62: Jamaica (Nominatim)
✓ 59/62: Namibia (Nominatim)
✓ 60/62: Botswana (Nominatim)
  Progress: 60/62 completed in 73.0s
✓ 61/62: Singapore (Nominatim)
✓ 62/62: Colombia (Nominatim)

Geocoding completed! Success rate: 20097/122633 (16.4%)
Excluded 77367 records with geographical_region = 'NR'

In [28]:
agmp_data_wip.loc[:,["latitude_03","longitude_03"]]

        latitude_03  longitude_03
0               NaN           NaN
1         35.000074    104.999927
2               NaN           NaN
3               NaN           NaN
4               NaN           NaN
...             ...           ...
199995          NaN           NaN
199996          NaN           NaN
199997          NaN           NaN
199998          NaN           NaN
199999          NaN           NaN

[200000 rows x 2 columns]

In [29]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_04' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_04' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_04'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp04")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_04'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_04'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_04', 'longitude_04']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_04'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_04'] = pd.to_numeric(agmp_data_wip['latitude_04'], errors='coerce')
agmp_data_wip['longitude_04'] = pd.to_numeric(agmp_data_wip['longitude_04'], errors='coerce')

Processing 51 valid addresses out of 51 total unique entries.
✓ 1/51: Estonia (Nominatim)
✓ 2/51: U.S. (Nominatim)
✓ 3/51: Netherlands (Nominatim)
✓ 4/51: Canada (Nominatim)
✓ 5/51: Finland (Nominatim)
  Progress: 5/51 completed in 4.9s
✓ 6/51: Denmark (Nominatim)
✓ 7/51: Ghana (Nominatim)
✓ 8/51: Uganda (Nominatim)
✓ 9/51: Switzerland (Nominatim)
✓ 10/51: Japan (Nominatim)
  Progress: 10/51 completed in 10.9s
✓ 11/51: South Africa (Nominatim)
✓ 12/51: France (Nominatim)
✓ 13/51: Australia (Nominatim)
✓ 14/51: Saudi Arabia (Nominatim)
✓ 15/51: U.K. (Nominatim)
  Progress: 15/51 completed in 17.1s
✓ 16/51: United Republic of Tanzania (Nominatim)
✓ 17/51: Liechtenstein (Nominatim)
✓ 18/51: Germany (Nominatim)
✓ 19/51: Norway (Nominatim)
✓ 20/51: NR (Nominatim)
  Progress: 20/51 completed in 23.0s
✓ 21/51: Egypt (Nominatim)
✓ 22/51: Italy (Nominatim)
✓ 23/51: Sweden (Nominatim)
✓ 24/51: Belgium (Nominatim)
✓ 25/51: Republic of Korea (Nominatim)
  Progress: 25/51 completed in 29.1s
✓ 26/51: Nigeria (Nominatim)
✓ 27/51: Colombia (Nominatim)
✓ 28/51: Brazil (Nominatim)
✓ 29/51: Kenya (Nominatim)
✓ 30/51: Iran (Islamic Republic of) (Nominatim)
  Progress: 30/51 completed in 35.1s
✓ 31/51: Poland (Nominatim)
✓ 32/51: Bangladesh (Nominatim)
✓ 33/51: Iceland (Nominatim)
✓ 34/51: Romania (Nominatim)
✓ 35/51: Peru (Nominatim)
  Progress: 35/51 completed in 42.2s
✓ 36/51: Greece (Nominatim)
✓ 37/51: Ukraine (Nominatim)
✓ 38/51: Austria (Nominatim)
✓ 39/51: Portugal (Nominatim)
✓ 40/51: Thailand (Nominatim)
  Progress: 40/51 completed in 47.2s
✓ 41/51: China (Nominatim)
✓ 42/51: Republic of Ireland (Nominatim)
✓ 43/51: Sudan (Nominatim)
✓ 44/51: Spain (Nominatim)
✓ 45/51: Philippines (Nominatim)
  Progress: 45/51 completed in 53.2s
✓ 46/51: American Samoa (Nominatim)
✓ 47/51: Tajikistan (Nominatim)
✓ 48/51: Sierra Leone (Nominatim)
✓ 49/51: Hungary (Nominatim)
✓ 50/51: Serbia (Nominatim)
  Progress: 50/51 completed in 59.2s
✓ 51/51: Argentina (Nominatim)

Geocoding completed! Success rate: 16944/122633 (13.8%)
Excluded 77367 records with geographical_region = 'NR'

In [30]:
agmp_data_wip.loc[:,["latitude_04","longitude_04"]]

        latitude_04  longitude_04
0               NaN           NaN
1         58.752378     25.331908
2               NaN           NaN
3               NaN           NaN
4               NaN           NaN
...             ...           ...
199995          NaN           NaN
199996          NaN           NaN
199997          NaN           NaN
199998          NaN           NaN
199999          NaN           NaN

[200000 rows x 2 columns]

In [31]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_05' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_05' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_05'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp05")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_05'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_05'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_05', 'longitude_05']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_05'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_05'] = pd.to_numeric(agmp_data_wip['latitude_05'], errors='coerce')
agmp_data_wip['longitude_05'] = pd.to_numeric(agmp_data_wip['longitude_05'], errors='coerce')

Processing 45 valid addresses out of 45 total unique entries.
✓ 1/45: U.S. (Nominatim)
✓ 2/45: El Salvador (Nominatim)
✓ 3/45: Finland (Nominatim)
✓ 4/45: Germany (Nominatim)
✓ 5/45: Netherlands (Nominatim)
  Progress: 5/45 completed in 4.9s
✓ 6/45: Estonia (Nominatim)
✓ 7/45: Denmark (Nominatim)
✓ 8/45: Canada (Nominatim)
✓ 9/45: Norway (Nominatim)
✓ 10/45: Ghana (Nominatim)
  Progress: 10/45 completed in 10.9s
✓ 11/45: Australia (Nominatim)
✓ 12/45: U.K. (Nominatim)
✓ 13/45: Belgium (Nominatim)
✓ 14/45: United Arab Emirates (Nominatim)
✓ 15/45: France (Nominatim)
  Progress: 15/45 completed in 17.3s
✓ 16/45: Brazil (Nominatim)
✓ 17/45: China (Nominatim)
✓ 18/45: Kenya (Nominatim)
✓ 19/45: Nigeria (Nominatim)
✓ 20/45: Croatia (Nominatim)
  Progress: 20/45 completed in 23.0s
✓ 21/45: Poland (Nominatim)
✓ 22/45: Japan (Nominatim)
✓ 23/45: Serbia (Nominatim)
✓ 24/45: Guatemala (Nominatim)
✓ 25/45: India (Nominatim)
  Progress: 25/45 completed in 29.1s
✓ 26/45: Czech Republic (Nominatim)
✓ 27/45: NR (Nominatim)
✓ 28/45: Iceland (Nominatim)
✓ 29/45: Greece (Nominatim)
✓ 30/45: Hungary (Nominatim)
  Progress: 30/45 completed in 35.0s
✓ 31/45: Costa Rica (Nominatim)
✓ 32/45: Spain (Nominatim)
✓ 33/45: Uzbekistan (Nominatim)
✓ 34/45: The former Yugoslav Republic of Macedonia (ArcGIS)
✓ 35/45: Cuba (Nominatim)
  Progress: 35/45 completed in 41.1s
✓ 36/45: Philippines (Nominatim)
✓ 37/45: Burkina Faso (Nominatim)
✓ 38/45: South Africa (Nominatim)
✓ 39/45: Italy (Nominatim)
✓ 40/45: Sweden (Nominatim)
  Progress: 40/45 completed in 47.0s
✓ 41/45: Thailand (Nominatim)
✓ 42/45: Cook Islands (Nominatim)
✓ 43/45: Austria (Nominatim)
✓ 44/45: Armenia (Nominatim)
✓ 45/45: Ethiopia (Nominatim)
  Progress: 45/45 completed in 53.1s

Geocoding completed! Success rate: 15185/122633 (12.4%)
Excluded 77367 records with geographical_region = 'NR'

In [32]:
agmp_data_wip.loc[:,["latitude_05","longitude_05"]]

        latitude_05  longitude_05
0               NaN           NaN
1          39.78373   -100.445882
2               NaN           NaN
3               NaN           NaN
4               NaN           NaN
...             ...           ...
199995          NaN           NaN
199996          NaN           NaN
199997          NaN           NaN
199998          NaN           NaN
199999          NaN           NaN

[200000 rows x 2 columns]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_06' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_06' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_06'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp06")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_06'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_06'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_06', 'longitude_06']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_06'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_06'] = pd.to_numeric(agmp_data_wip['latitude_06'], errors='coerce')
agmp_data_wip['longitude_06'] = pd.to_numeric(agmp_data_wip['longitude_06'], errors='coerce')

Processing 51 valid addresses out of 51 total unique entries.
✓ 1/51: Finland (Nominatim)
✓ 2/51: Panama (Nominatim)
✓ 3/51: Canada (Nominatim)
✓ 4/51: Germany (Nominatim)
✓ 5/51: U.K. (Nominatim)
  Progress: 5/51 completed in 4.9s
✓ 6/51: Netherlands (Nominatim)
✓ 7/51: Sweden (Nominatim)
✓ 8/51: Democratic Republic of the Congo (Nominatim)
✓ 9/51: Belgium (Nominatim)
✓ 10/51: Denmark (Nominatim)
  Progress: 10/51 completed in 10.9s
✓ 11/51: Barbados (Nominatim)
✓ 12/51: France (Nominatim)
✓ 13/51: Switzerland (Nominatim)
✓ 14/51: Japan (Nominatim)
✓ 15/51: Spain (Nominatim)
  Progress: 15/51 completed in 17.0s
✓ 16/51: U.S. (Nominatim)
✓ 17/51: Norway (Nominatim)
✓ 18/51: Peru (Nominatim)
✓ 19/51: The former Yugoslav Republic of Macedonia (ArcGIS)
✓ 20/51: Nigeria (Nominatim)
  Progress: 20/51 completed in 23.0s
✓ 21/51: Iceland (Nominatim)
✓ 22/51: Ecuador (Nominatim)
✓ 23/51: Pakistan (Nominatim)
✓ 24/51: Philippines (Nominatim)
✓ 25/51: Singapore (Nominatim)
  Progress: 25/51 completed in 29.0s
✓ 26/51: Estonia (Nominatim)
✓ 27/51: Malawi (Nominatim)
✓ 28/51: Slovakia (Nominatim)
✓ 29/51: Republic of Ireland (Nominatim)
✓ 30/51: Argentina (Nominatim)
  Progress: 30/51 completed in 35.3s
✓ 31/51: NR (Nominatim)
✓ 32/51: Turkey (Nominatim)
✓ 33/51: Lithuania (Nominatim)

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Georgia',), **{}).
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Georgia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Georgia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Georgia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

✓ 34/51: Georgia (Nominatim)
✓ 35/51: Italy (Nominatim)
  Progress: 35/51 completed in 49.1s
✓ 36/51: Czech Republic (Nominatim)
✓ 37/51: Kenya (Nominatim)
✓ 38/51: Taiwan (Nominatim)
✓ 39/51: United Republic of Tanzania (Nominatim)
✓ 40/51: Uganda (Nominatim)
  Progress: 40/51 completed in 55.2s
✓ 41/51: Viet Nam (Nominatim)

In [ ]:
agmp_data_wip.loc[:,["latitude_06","longitude_06"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_07' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_07' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_07'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp07")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_07'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_07'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_07', 'longitude_07']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_07'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_07'] = pd.to_numeric(agmp_data_wip['latitude_07'], errors='coerce')
agmp_data_wip['longitude_07'] = pd.to_numeric(agmp_data_wip['longitude_07'], errors='coerce')

In [ ]:

agmp_data_wip.loc[:,["latitude_07","longitude_07"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_08' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_08' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_08'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp08")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_08'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_08'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_08', 'longitude_08']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_08'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_08'] = pd.to_numeric(agmp_data_wip['latitude_08'], errors='coerce')
agmp_data_wip['longitude_08'] = pd.to_numeric(agmp_data_wip['longitude_08'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_08","longitude_08"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_09' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_09' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_09'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp09")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_09'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_09'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_09', 'longitude_09']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_09'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_09'] = pd.to_numeric(agmp_data_wip['latitude_09'], errors='coerce')
agmp_data_wip['longitude_09'] = pd.to_numeric(agmp_data_wip['longitude_09'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_09","longitude_09"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_010' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_010' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_010'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp10")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_10'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_10'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_10', 'longitude_10']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_10'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_10'] = pd.to_numeric(agmp_data_wip['latitude_10'], errors='coerce')
agmp_data_wip['longitude_10'] = pd.to_numeric(agmp_data_wip['longitude_10'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_10","longitude_10"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_011' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_011' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_011'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp11")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_11'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_11'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_11', 'longitude_11']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_11'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_11'] = pd.to_numeric(agmp_data_wip['latitude_11'], errors='coerce')
agmp_data_wip['longitude_11'] = pd.to_numeric(agmp_data_wip['longitude_11'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_11","longitude_11"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_012' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_012' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_012'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp12")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_12'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_12'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_12', 'longitude_12']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_12'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_12'] = pd.to_numeric(agmp_data_wip['latitude_12'], errors='coerce')
agmp_data_wip['longitude_12'] = pd.to_numeric(agmp_data_wip['longitude_12'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_12","longitude_12"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_013' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_013' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_013'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp13")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_13'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_13'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_13', 'longitude_13']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_13'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_13'] = pd.to_numeric(agmp_data_wip['latitude_13'], errors='coerce')
agmp_data_wip['longitude_13'] = pd.to_numeric(agmp_data_wip['longitude_13'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_13","longitude_13"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_014' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_014' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_014'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp14")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 4. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_14'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_14'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_14', 'longitude_14']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_14'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_14'] = pd.to_numeric(agmp_data_wip['latitude_14'], errors='coerce')
agmp_data_wip['longitude_14'] = pd.to_numeric(agmp_data_wip['longitude_14'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_14","longitude_14"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_015' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_015' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_015'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp15")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 5. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.5)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 5. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 5 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_15'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_15'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_15', 'longitude_15']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_15'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_15'] = pd.to_numeric(agmp_data_wip['latitude_15'], errors='coerce')
agmp_data_wip['longitude_15'] = pd.to_numeric(agmp_data_wip['longitude_15'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_15","longitude_15"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_016' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_016' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_016'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp16")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 6. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.6)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 6. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 6 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 6. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_16'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_16'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_16', 'longitude_16']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_16'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_16'] = pd.to_numeric(agmp_data_wip['latitude_16'], errors='coerce')
agmp_data_wip['longitude_16'] = pd.to_numeric(agmp_data_wip['longitude_16'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_16","longitude_16"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_017' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_017' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_017'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp17")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 7. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.7)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 7. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 7 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 7. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 7. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_17'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_17'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_17', 'longitude_17']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_17'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_17'] = pd.to_numeric(agmp_data_wip['latitude_17'], errors='coerce')
agmp_data_wip['longitude_17'] = pd.to_numeric(agmp_data_wip['longitude_17'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_17","longitude_17"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_018' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_018' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_018'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp18")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 8. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.8)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 8. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 8 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 8. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 8. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_18'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_18'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 8. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_18', 'longitude_18']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_18'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_18'] = pd.to_numeric(agmp_data_wip['latitude_18'], errors='coerce')
agmp_data_wip['longitude_18'] = pd.to_numeric(agmp_data_wip['longitude_18'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_18","longitude_18"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_019' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_019' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_019'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp19")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_19'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_19'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_19', 'longitude_19']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_19'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_19'] = pd.to_numeric(agmp_data_wip['latitude_19'], errors='coerce')
agmp_data_wip['longitude_19'] = pd.to_numeric(agmp_data_wip['longitude_19'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_19","longitude_19"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_020' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_020' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_020'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp20")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_20'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_20'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_20', 'longitude_20']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_20'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_20'] = pd.to_numeric(agmp_data_wip['latitude_20'], errors='coerce')
agmp_data_wip['longitude_20'] = pd.to_numeric(agmp_data_wip['longitude_20'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_20","longitude_20"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_021' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_021' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_021'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp21")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_21'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_21'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_21', 'longitude_21']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_21'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_21'] = pd.to_numeric(agmp_data_wip['latitude_21'], errors='coerce')
agmp_data_wip['longitude_21'] = pd.to_numeric(agmp_data_wip['longitude_21'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_21","longitude_21"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_022' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_022' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_022'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp22")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_22'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_22'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_22', 'longitude_22']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_22'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_22'] = pd.to_numeric(agmp_data_wip['latitude_22'], errors='coerce')
agmp_data_wip['longitude_22'] = pd.to_numeric(agmp_data_wip['longitude_22'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_22","longitude_22"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_023' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_023' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_023'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp23")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_23'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_23'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_23', 'longitude_23']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_23'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_23'] = pd.to_numeric(agmp_data_wip['latitude_23'], errors='coerce')
agmp_data_wip['longitude_23'] = pd.to_numeric(agmp_data_wip['longitude_23'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_23","longitude_23"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_024' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_024' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_024'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp24")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_24'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_24'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_24', 'longitude_24']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_24'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_24'] = pd.to_numeric(agmp_data_wip['latitude_24'], errors='coerce')
agmp_data_wip['longitude_24'] = pd.to_numeric(agmp_data_wip['longitude_24'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_24","longitude_24"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_025' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_025' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_025'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp25")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_25'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_25'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_25', 'longitude_25']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_25'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_25'] = pd.to_numeric(agmp_data_wip['latitude_25'], errors='coerce')
agmp_data_wip['longitude_25'] = pd.to_numeric(agmp_data_wip['longitude_25'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_25","longitude_25"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_026' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_026' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_026'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp26")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_26'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_26'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_26', 'longitude_26']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_26'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_26'] = pd.to_numeric(agmp_data_wip['latitude_26'], errors='coerce')
agmp_data_wip['longitude_26'] = pd.to_numeric(agmp_data_wip['longitude_26'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_26","longitude_26"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_027' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_027' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_027'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp27")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_27'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_27'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_27', 'longitude_27']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_27'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_27'] = pd.to_numeric(agmp_data_wip['latitude_27'], errors='coerce')
agmp_data_wip['longitude_27'] = pd.to_numeric(agmp_data_wip['longitude_27'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_27","longitude_27"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_028' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_028' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_028'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp28")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_28'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_28'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_28', 'longitude_28']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_28'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_28'] = pd.to_numeric(agmp_data_wip['latitude_28'], errors='coerce')
agmp_data_wip['longitude_28'] = pd.to_numeric(agmp_data_wip['longitude_28'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_28","longitude_28"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_029' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_029' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_029'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp29")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_29'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_29'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_29', 'longitude_29']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_29'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_29'] = pd.to_numeric(agmp_data_wip['latitude_29'], errors='coerce')
agmp_data_wip['longitude_29'] = pd.to_numeric(agmp_data_wip['longitude_29'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_29","longitude_29"]]

In [ ]:
# =========================================================
# Geocoding with handling for geographical_region = "NR" (for agmp_data_wip)
# =========================================================
from geopy.geocoders import Nominatim, ArcGIS
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError
import pandas as pd
import numpy as np
import time

# =========================================================
# 1. Safety checks
# =========================================================
if 'agmp_data_wip' not in globals():
    raise NameError("agmp_data_wip is not defined. Please ensure your DataFrame is loaded.")

# Remove duplicate columns
agmp_data_wip = agmp_data_wip.loc[:, ~agmp_data_wip.columns.duplicated()]

if 'country_participant_030' not in agmp_data_wip.columns:
    raise KeyError("Column 'country_participant_030' not found in agmp_data_wip.")

# Force Series (avoids .unique() error)
participant_series = pd.Series(agmp_data_wip['country_participant_030'])

# =========================================================
# 2. Prepare address list
# =========================================================
addresses = participant_series.dropna().astype(str)
valid_addresses = [addr.strip() for addr in addresses if addr.strip() and len(addr.strip()) > 1]
valid_addresses = pd.Series(valid_addresses).unique()

print(f"Processing {len(valid_addresses)} valid addresses out of {len(addresses.unique())} total unique entries.")

# =========================================================
# 3. Initialize geocoders
# =========================================================
primary_geolocator = Nominatim(user_agent="myApp30")
primary_geocode = RateLimiter(primary_geolocator.geocode, min_delay_seconds=1.2)
fallback_geolocator = ArcGIS(scheme="https")
fallback_geocode = RateLimiter(fallback_geolocator.geocode, min_delay_seconds=1.2)

# =========================================================
# 9. Geocoding cache
# =========================================================
location_cache = {}

def geocode_with_fallback(address):
    """Try Nominatim first, then ArcGIS if it fails"""
    cleaned_address = str(address).strip()

    # Primary: Nominatim
    try:
        location = primary_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "Nominatim")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  Nominatim failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  Nominatim unexpected error for '{cleaned_address}': {e}")

    # Fallback: ArcGIS
    try:
        time.sleep(0.9)
        location = fallback_geocode(cleaned_address)
        if location:
            return (location.latitude, location.longitude, "ArcGIS")
    except (GeocoderQueryError, GeocoderTimedOut, GeocoderServiceError) as e:
        print(f"  ArcGIS failed for '{cleaned_address}': {e}")
    except Exception as e:
        print(f"  ArcGIS unexpected error for '{cleaned_address}': {e}")

    return (np.nan, np.nan, "Failed")

# =========================================================
# 9. Geocode loop
# =========================================================
start_time = time.time()
for i, address in enumerate(valid_addresses):
    lat, lon, source = geocode_with_fallback(address)
    location_cache[address] = (lat, lon)

    if pd.notna(lat):
        print(f"✓ {i+1}/{len(valid_addresses)}: {address} ({source})")
    else:
        print(f"✗ {i+1}/{len(valid_addresses)}: {address} (not found)")

    if (i + 1) % 9 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1}/{len(valid_addresses)} completed in {elapsed:.1f}s")

# =========================================================
# 9. Fill cache for invalid addresses
# =========================================================
for address in addresses.unique():
    if address not in location_cache:
        location_cache[address] = (np.nan, np.nan)

# =========================================================
# 9. Map results to DataFrame (lat first, lon second)
# =========================================================
agmp_data_wip['latitude_30'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[0])
agmp_data_wip['longitude_30'] = participant_series.map(lambda x: location_cache.get(str(x).strip(), (np.nan, np.nan))[1])

# =========================================================
# 9. Handle geographical_region = "NR"
# =========================================================
nr_count = 0
if 'geographical_region' in agmp_data_wip.columns:
    nr_mask = agmp_data_wip['geographical_region'].astype(str).str.upper() == "NR"
    agmp_data_wip.loc[nr_mask, ['latitude_30', 'longitude_30']] = np.nan
    nr_count = nr_mask.sum()
    valid_mask = ~nr_mask
else:
    valid_mask = pd.Series(True, index=agmp_data_wip.index)

# =========================================================
# 9. Success rate (excluding NR)
# =========================================================
successful_geocodes = agmp_data_wip.loc[valid_mask, 'latitude_30'].notna().sum()
total_valid_rows = valid_mask.sum()

if total_valid_rows > 0:
    success_rate = (successful_geocodes / total_valid_rows) * 100
    print(f"\nGeocoding completed! Success rate: {successful_geocodes}/{total_valid_rows} ({success_rate:.1f}%)")
    if nr_count > 0:
        print(f"Excluded {nr_count} records with geographical_region = 'NR'")
else:
    print("\nGeocoding completed! No valid addresses to geocode.")

# =========================================================
# 10. Ensure numeric dtypes
# =========================================================
agmp_data_wip['latitude_30'] = pd.to_numeric(agmp_data_wip['latitude_30'], errors='coerce')
agmp_data_wip['longitude_30'] = pd.to_numeric(agmp_data_wip['longitude_30'], errors='coerce')

In [ ]:
agmp_data_wip.loc[:,["latitude_30","longitude_30"]]

In [ ]:
agmp_data_wip.head()

In [ ]:
agmp_data_final = agmp_data_wip

In [ ]:
agmp_data_final

In [ ]:
agmp_data_final.columns

In [ ]:
excel_filename = 'second_import_job_run.xlsx'

In [ ]:

agmp_data_final.to_excel(excel_filename, index=False)

In [ ]:
# =========================================================
# Export into chunks of 50,000 record files each
# =========================================================
import pandas as pd
import math

# Get the dataframe
agmp_data_final = agmp_data_final  # Your existing dataframe

# Define the chunk size
chunk_size = 50000

# Calculate the number of files needed
num_files = math.ceil(len(agmp_data_final) / chunk_size)

# Split and export the dataframe
for i in range(num_files):
    # Calculate start and end indices
    start_idx = i * chunk_size
    end_idx = min((i + 1) * chunk_size, len(agmp_data_final))
    
    # Slice the dataframe
    chunk = agmp_data_final.iloc[start_idx:end_idx]
    
    # Create filename with simplified naming: part_2_1, part_2_2, etc.
    filename = f'second_import_job_run_part_2_{i+1}.xlsx'
    
    # Export to Excel
    chunk.to_excel(filename, index=False)
    
    print(f'Exported {filename}: {len(chunk)} records (rows {start_idx+1} to {end_idx})')

print(f'\nTotal records: {len(agmp_data_final)}')
print(f'Files created: {num_files}')
print(f'Chunk size: {chunk_size}')

# Optional: Print summary of all files
print('\nFiles created:')
for i in range(num_files):
    print(f'  - second_import_job_run_part_2_{i+1}.xlsx')